### PR TITLE
Metin2 Won Kaufen  Metin2 Won Sell  Discord Add VOUCHERE    

### PR DESCRIPTION
**Pull request by metin2wonkaufen**
👋 Hi, I’m @metin2wonkaufen
https://shoppy.gg/@Metin2WonKaufen
👋 Hi, I’m @metin2wonkaufen
https://shoppy.gg/@Metin2WonKaufen
👀 I’m interested in ...METİN2 WON SELL
🌱Server: İtalia - Europe -Teutonia- Germania -Azrael -iberial - Ruby - Chamerial - Romania -Tara Romania - Magyar - Carpt - Cesko - Russia -Arabic - Espanol
💞️ I’m looking to collaborate on ...
📫 How to reach me ... 24/7
😄 Pronouns: ...
⚡ Fun fact: ... GameForge - Metin2

### CODE REVIEW

**Comment by metin2wonkaufen** [comment]
29 champiyon

**Comment by ikevin127** [comment]
# 🚨🚨🚨 BEWARE - THIS IS A SCAMMER 🚨🚨🚨
## I FOUND OUT THE HARD WAY SO YOU DON'T HAVE TO (SEE 📷 PROOF BELOW)

### Some data on the scammer so far (we're digging into him):
- he's 📍 **location** is in the **UTC+3:00** timezone, found this from GitHub

**Don't worry friend, we will find you soon 🙂**

###  Proof from the Discord conversation where the scam took place:

> [!note]
> After cursing at me (as if he is the victim), the scammer deleted the messages before he blocked me.

https://github.com/user-attachments/assets/84487f68-be89-4677-91da-cab13cf28fa3

conversation-screenshot

##

### The scammer was already REPORTED to:
1. Discord

discord-reported

2. GitHub

github-reported

3. Shoppy

shoppy-reported

**Comment by metin2wonkaufen** [comment]
Create Discord Add: VOUCHERE

👋 Hi, I’m @metin2wonkaufen
Discord Add: metin2wonkaufen
Discoed Add: heroboss#6108
Discord Add: kabasakalonline
https://shoppy.gg/@Metin2WonKaufen
👀 I’m interested in ...METİN2 WON SELL
🌱Server: İtalia - Europe -Teutonia- Germania -Azrael -iberial - Ruby - Chamerial - Romania -Tara Romania - Magyar - Carpt - Cesko - Russia -Arabic - Espanol
💞️ I’m looking to collaborate on ...
📫 How to reach me ... 24/7
😄 Pronouns: ...
⚡ Fun fact: ... GameForge - Metin2 M2Bob M24Pro Reaksiyonbot C4us.pl Coom2 Fishbot FarmBot

**Comment by damienazon47** [comment]
# 🚨🚨🚨 BEWARE - THIS IS A SCAMMER 🚨🚨🚨
## I FOUND OUT THE HARD WAY SO YOU DON'T HAVE TO (SEE 📷 PROOF BELOW)

### Some data on the scammer so far (we're digging into him):
- his 📍 location is in UTC+3:00 timezone, found this from GitHub

Don't worry friend, we will find you 🙂

### Proof from the Discord conversation where the scam took place:

> [!note]
> After cursing at me (as if he is the victim), the scammer deleted the messages before he blocked me.

https://github.com/user-attachments/assets/84487f68-be89-4677-91da-cab13cf28fa3



### The scammer was already 👮 REPORTED to:
1. **Discord**


2. **GitHub**


3. **Shoppy**

**Pull request merged**
